holoviz/holonote

- holonote/annotate/annotator.py
Small convenience functionality that deselects the annotated region with a double tap.
> Add double tap to deselect

- .github/workflows/test.yaml
- holonote/annotate/table.py
- holonote/tests/test_connectors.py
- pyproject.toml
Code changes are to support Pandas 2 (see traceback). I tested and confirmed the changes also worked with Pandas 1.
<details>
<summary>Traceback </summary>
``` python
========================================================================================================================================= FAILURES =========================================================================================================================================
___________________________________________________________________________________________________________________ TestAnnotatorMultipleStringFields.test_commit_update ___________________________________________________________________________________________________________________
self = …
```
> Add Python 3.11 to tests and support Pandas 2

- holonote/annotate/annotator.py
- holonote/annotate/connector.py
- holonote/tests/test_annotators_basic.py
I'm not sure we should keep having fields in the `Connector`. 
This makes it possible to do this:
``` python
fields = ["ProductionStoppage", "Reason", "Category"]
connector = SQLiteDB(filename=":memory:")
annotator = Annotator({"TIME": float}, fields=fields, connector=connector)
> Use annotators fields if none is provided to the connector

- .github/workflows/build.yaml
- holonote/annotate/table.py
- holonote/tests/test_annotation_table.py
- pyproject.toml
<s> Needs to double-check if it is okay to set `self._field_df =new_fields` based on column names. </s>. 
Also took the time to update other CI related features in this PR.
> Add support for pandas 2.1

- holonote/annotate/annotator.py
- holonote/tests/test_annotators_advanced.py
It would give some unintuitive behavior:
``` python
import holoviews as hv
import pandas as pd
hv.extension("bokeh")
connector = SQLiteDB(filename=":memory:")
annotator = Annotator({"x": float}, connector=connector)
data = {"description": ["A", "B"], "start_number": [0.1, 0.5], "end_number": [0.4, 0.8]}
annotator.define_annotations(pd.DataFrame(data), x=("start_number", "end_number"))
hv.Curve([]) * annotator
```
Before:
https://github.com/holoviz/holonote/assets/19758978/d30d6f6e-d4e7-4a37-8fb7-09068d7d8bc9
After:
https://github.com/holoviz/holonote/assets/19758978/e4c374ad-18e0-41b6-bba0-5e7012fc157f
> Clear region after using define_annotations

- holonote/app/panel.py
In Panel 1.3, it is now possible to add descriptions to buttons. This will make it easier to show the intent between each button in the Panel app.
https://github.com/holoviz/holonote/assets/19758978/fa68fc68-c6f5-41af-8d85-9de189694985
> Add description to buttons in panel app

- holonote/app/panel.py
The `__panel__` method isn't useful unless the class inherits from `Viewer`.
> Fixed inheritance declaration of PanelWidgets

- .gitignore
- holonote/annotate/annotator.py
- holonote/annotate/display.py
- holonote/annotate/table.py
This will now only update the data of the display each time a `refresh()` is done and only refresh when `selected_indexes` is changed.
Something like this would run `self.annotator.get_dataframe` 5 times with each click on a curve. If I commented out the `anno2` line, it would be 3 times. After this change, it will only run once, and not update when clicking (as the data has not changed).
``` python
from __future__ import annotations
import holoviews as hv
import panel as pn
from holonote.app import PanelWidgets
hv.extension("bokeh")
connector = SQLiteDB(table_name="test_curves")
annotator = Annotator({"TIME": float}, fields=["description"], connector=connector)
anno1 = annotator * hv.Curve(range(10), kdims="TIME")
anno2 = annotator * …
```
> Reduce updating triggers for displays

- holonote/annotate/display.py
- holonote/tests/util.py
Having `static_indicator` as a property "hides" that it recreates a new element each time.  
I have simplified the logic by removing duplicated code and updated `get_indices_by_position` to no longer use `self.static_indicator.data`. Instead, it now uses the already available data.
Also, change `static_indicator` to a normal method and only create indicators once.
> Performance improvements related to static_indicators

- holonote/tests/benchmark/test_benchmarks.py
Because we "empty" the annotator when running `define_annoator` / `commit`,  we never really measured the time it took to run the critical part of the code.
> Add setup to benchmark

- holonote/annotate/connector.py
Fixes #8 
Also adds a `close` method to close the database connection.
> Use contextmanager for SQLite communication

- holonote/annotate/annotator.py
- holonote/annotate/connector.py
- holonote/tests/test_annotators_basic.py
This PR does the following:
- Don't send `None` values to the database when adding rows. This is already done by the database.
- Remove the `columns` property.
- Fixes a bug where `AnnotatorInterface` did not clear the region after adding an annotation, this bug did not affect the `Annotator` when using an element. 
Based on the `use_context` PR.
> Don't send `None` values to the database when adding new rows

- examples/tutorial/02_Multiple_Annotations.ipynb
- holonote/annotate/annotator.py
- holonote/annotate/display.py
- holonote/tests/test_annotators_element.py
- pyproject.toml
This will now make it easier to add across overlays and layouts.
> Improve the combination logic for overlaying an annotator

- holonote/annotate/display.py
- holonote/app/panel.py
- holonote/tests/test_annotators_style.py
Also, memorizing the color when using `groupby`  by using a dim expression instead of cycle.
https://github.com/holoviz/holonote/assets/19758978/c327741c-ed12-4797-83e6-e7a916ae6107
<details>
<summary>Code </summary>
``` python
import hvplot.pandas
import pandas as pd
from holonote.app import PanelWidgets
import panel as pn
speed_data = pd.read_parquet("../assets/example.parquet")
curve = speed_data.hvplot("TIME", "SPEED")
annotator = Annotator(
curve,
fields=["category"],
connector=SQLiteDB(table_name="styling"),
)
start_time = pd.date_range("2022-06-04", "2022-06-22", periods=5)
end_time = start_time + pd.Timedelta(days=2)
data = {
"start_time": start_time,
"end_time": end_time,
"category": ["A", "B", "A", "C", "B"],
} …
```
> Improve PanelWidgets with visible widget and make color deterministic

- holonote/annotate/display.py
Fixes https://github.com/holoviz/holonote/issues/103
This rewrites converts the last part to timedelta, making it possible to divide it.
> Update point calculation so it works for timeseries

- holonote/annotate/display.py
- holonote/tests/test_annotators_element.py
Make `_edit_streams` public by subsetting the relevant ones and returning a dict
> Public edit streams

- holonote/annotate/annotator.py
- holonote/annotate/display.py
- holonote/tests/test_annotators_element.py
- holonote/tests/util.py
Fixes https://github.com/holoviz/holonote/issues/112
Invert axis if the first kdim of the element is not an annotator kdim, ensuring overlaying annotations align with underlying elements.
<details> <summary> Code </summary>
```python
import holoviews as hv; hv.extension('bokeh')
import panel as pn; pn.extension()
import numpy as np
from holonote.annotate import Annotator
from holonote.app import PanelWidgets
annotator = Annotator({"x": float, "y": float}, fields=["description"])
bounds = (-1, -1, 1, 1)
data = np.array([[0, 1], [1, 0]])
img = hv.Image(data, kdims=['x', 'y'], bounds=bounds)
img_right = hv.Image(data, kdims=['z', 'y'], bounds=bounds)  # y as second kdim! so HSpan
left_plot = annotator * img
right_plot = annotator * img_right
layout = left_plot + right_plot …
```
> Conditionally invert axis to align annotations with elements

- holonote/app/panel.py
Fixes #110 
Note that it showed all colors before but collapsed them into one location...
> Fix visible indicator in Chrome

- holonote/annotate/display.py
- holonote/app/panel.py
Closes https://github.com/holoviz/holonote/issues/114 and makes the popup more robust across another example (region 2d) not from the tutorial.
https://github.com/holoviz/holonote/assets/15331990/99497a05-f6b0-44b5-a217-af1b6952a48f
The clipping of the popup panel at the edge of the plot is a HoloViews/Bokeh issue that will be addressed separately.
> Fix edit stream and make popup more robust

- holonote/annotate/display.py
- holonote/tests/test_display.py
https://github.com/holoviz/holonote/assets/15331990/86c6a298-eefc-4b3d-94d7-0486532ab17b
```python
from holonote.annotate import Annotator
from holonote.app import PanelWidgets
import xarray as xr
import panel as pn
import holoviews as hv
hv.extension("bokeh")
ds = xr.tutorial.open_dataset("air_temperature")
def plot_image(time):
image = hv.Image(ds.sel(time=time), ["lon", "lat"], ["air"]).opts(
cmap="RdBu_r",
title=time,
colorbar=True,
clim=(220, 340),
width=500,
height=300,
tools=["tap"],
)
return image
def plot_timeseries_by_select(indices):
if not indices:
return
if "start[lon]" in annotator.df.columns:
row = annotator.df.loc[indices[0]]
lon1 = row["start[lon]"]
lon2 = row["end[lon]"]
lat1 = row["start[lat]"]
lat2 = row["end[lat]"]
ds_sel = ds.sel(lon=slice(lon1, lon2), …
```
> Support points 2d

- holonote/annotate/display.py
- holonote/tests/test_annotators_element.py
Fixes #119
Fix error when creating a new annotation from an empty annotator overlaid on an element and when .groupby has been set
> Handle empty indicator when groupby is set

- examples/tutorial/04_Make_an_App.ipynb
- examples/tutorial/05_Watch_Events.ipynb
- holonote/annotate/annotator.py
- holonote/app/__init__.py
- holonote/app/tabulator.py
- holonote/tests/test_annotators_advanced.py
- holonote/tests/test_app.py
TODOS:
Delete rows from the tabulator
https://github.com/holoviz/holonote/assets/19758978/eca71408-7420-4420-9fb0-e03f08f58edb
Edit values from tabulator + sync of selection
https://github.com/holoviz/holonote/assets/19758978/2425ef01-146d-4ba1-9714-5f666acdf7c6
<details>
<summary>Code </summary>
``` python
import hvplot.pandas
import pandas as pd
speed_data = pd.read_parquet("../assets/example.parquet")
curve = speed_data.hvplot("TIME", "SPEED")
annotator = Annotator(
curve,
fields=["category"],
connector=SQLiteDB(table_name="styling"),
)
start_time = pd.date_range("2022-06-04", "2022-06-22", periods=5)
end_time = start_time + pd.Timedelta(days=2)
data = {
"start_time": start_time,
"end_time": end_time,
"category": ["A", "B", "A", "C", …
```
> Add Tabulator app

- holonote/app/tabulator.py
Fixes #125 
Use `tabulator_kwargs` and refer to the options https://panel.holoviz.org/reference/widgets/Tabulator.html
TODO:
For instance:
```python
AnnotatorTable(annotator, tabulator_kwargs=dict(pagination='local', page_size=7))
```
<details> <summary> Code </summary>
```python
import panel as pn
import holoviews as hv
hv.extension('bokeh')
import pandas as pd
from holonote.annotate import Annotator
from holonote.annotate.connector import SQLiteDB
from holonote.app import PanelWidgets, AnnotatorTable
data = {
'description': ['T0', 'T1', 'T2'] * 10,
'start': range(30),
'end': [i + .8 for i in range(30)]
}
annotations_df = pd.DataFrame(data)
curve_data = {
'time': range(30),
'val': [1, 3, 2] * 10,
}
curve_df = pd.DataFrame(curve_data)
plot = hv.Curve(curve_df, 'time', 'val')
annotator = …
```
> Add support for custom tabulator options

- holonote/annotate/display.py
- holonote/app/panel.py
- holonote/app/tabulator.py
- holonote/tests/conftest.py
- holonote/tests/test_annotators_style.py
Fixes https://github.com/holoviz/holonote/issues/124
Previously, the PanelWidgets' Visibility UI did not update when new annotations were added/removed/changed. This PR attempts to synchronize the visibility UI with annotator events: create, delete, and update (edit).
I've also changed how tabulator on_edit triggers events.. previously any change was triggering both field and region update events, and now it's either one xor the other.
I've also moved the legend color circles to the left of the visibility UI instead of the right, given that if you added more than 4 groupby field types, then a scrollbar appears and obscures the legend color circles on the right. The aesthetics of this can still be much improved, but at least it's not interfering now.
TODO: 
<details> <summary> Code …
> Update visible UI from annotator events

- holonote/annotate/annotator.py
- holonote/annotate/display.py
- holonote/tests/test_annotators_element.py
- holonote/tests/test_annotators_style.py
- holonote/tests/util.py
- pyproject.toml
> Don't show all elements if nothing is selected by visibile
